In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\Public\Documents\Axel\wcup26\matchStats\csv\fotmob_match_stats.csv')
df

,matchId,matchRound,homeTeamName,homeTeamid,awayTeamName,awayTeamid,home_goals,away_goals,ball_possession_home,ball_possession_away,...,ground_duels_won_home,ground_duels_won_away,aerial_won_home,aerial_won_away,dribbles_succeeded_home,dribbles_succeeded_away,yellow_cards_home,yellow_cards_away,red_cards_home,red_cards_away
0,4667751,1,Mexico,6710,South Africa,6316,2,0,60,40,...,32 (55%),26 (45%),15 (68%),7 (32%),9 (60%),1 (17%),1,2,1,2
1,4667752,1,South Korea,7804,Czechia,8496,2,1,62,38,...,29 (57%),22 (43%),27 (63%),16 (37%),8 (57%),4 (57%),1,0,0,0
2,4667757,1,Canada,5810,Bosnia and Herzegovina,10106,1,1,61,39,...,50 (58%),36 (42%),20 (32%),43 (68%),7 (47%),5 (23%),2,3,0,0
3,4667771,1,USA,6713,Paraguay,6724,4,1,65,35,...,47 (55%),39 (45%),18 (53%),16 (47%),22 (63%),6 (60%),1,5,0,0
4,4667758,1,Qatar,5902,Switzerland,6717,1,1,32,68,...,26 (49%),27 (51%),10 (50%),10 (50%),2 (50%),7 (54%),2,1,0,0
5,4667764,1,Brazil,8256,Morocco,6262,1,1,51,49,...,41 (41%),58 (59%),12 (75%),4 (25%),5 (19%),16 (55%),2,0,0,0
6,4667765,1,Haiti,5934,Scotland,8498,0,1,54,46,...,38 (50%),38 (50%),13 (38%),21 (62%),6 (43%),5 (38%),1,3,0,0
7,4667772,1,Australia,6716,Turkiye,6595,2,0,28,72,...,27 (48%),29 (52%),15 (47%),17 (53%),8 (73%),5 (36%),0,1,0,0
8,4667777,1,Germany,8570,Curacao,287981,7,1,65,35,...,38 (46%),45 (54%),9 (64%),5 (36%),9 (50%),12 (57%),0,0,0,0
9,4667783,1,Netherlands,6708,Japan,6715,2,2,60,40,...,25 (54%),21 (46%),21 (75%),7 (25%),8 (53%),3 (33%),3,0,0,0
10,4667778,1,Ivory Coast,6709,Ecuador,6707,1,0,48,52,...,41 (55%),33 (45%),17 (61%),11 (39%),14 (67%),3 (30%),3,1,0,0
11,4667784,1,Sweden,8520,Tunisia,6719,5,1,49,51,...,26 (42%),36 (58%),15 (50%),15 (50%),5 (42%),7 (44%),0,1,0,0
12,4667798,1,Spain,6720,Cape Verde,5888,0,0,74,26,...,21 (40%),31 (60%),19 (68%),9 (32%),7 (54%),4 (36%),1,1,0,0
13,4667790,1,Belgium,8263,Egypt,10255,1,1,54,46,...,38 (44%),49 (56%),14 (64%),8 (36%),7 (37%),7 (54%),2,2,0,0
14,4667799,1,Saudi Arabia,7795,Uruguay,5796,1,1,33,67,...,18 (45%),22 (55%),22 (52%),20 (48%),3 (60%),8 (67%),1,0,0,0

In [3]:
df.columns

Index(['matchId', 'matchRound', 'homeTeamName', 'homeTeamid', 'awayTeamName',
       'awayTeamid', 'home_goals', 'away_goals', 'ball_possession_home',
       'ball_possession_away', 'big_chances_home', 'big_chances_away',
       'big_chances_missed_home', 'big_chances_missed_away', 'fouls_home',
       'fouls_away', 'corners_home', 'corners_away', 'total_shots_home',
       'total_shots_away', 'shots_off_target_home', 'shots_off_target_away',
       'shots_on_target_home', 'shots_on_target_away', 'blocked_shots_home',
       'blocked_shots_away', 'hit_woodwork_home', 'hit_woodwork_away',
       'shots_inside_box_home', 'shots_inside_box_away',
       'shots_outside_box_home', 'shots_outside_box_away', 'xG_home',
       'xG_away', 'xG_open_play_home', 'xG_open_play_away', 'xG_set_play_home',
       'xG_set_play_away', 'xG_non_penalty_home', 'xG_non_penalty_away',
       'xGOT_home', 'xGOT_away', 'passes_home', 'passes_away',
       'accurate_passes_home', 'accurate_passes_away', 'own_half_passes_home',
       'own_half_passes_away', 'opposition_half_passes_home',
       'opposition_half_passes_away', 'accurate_long_passes_home',
       'accurate_long_passes_away', 'accurate_crosses_home',
       'accurate_crosses_away', 'throws_home', 'throws_away',
       'touches_opp_box_home', 'touches_opp_box_away', 'offsides_home',
       'offsides_away', 'tackles_won_home', 'tackles_won_away',
       'interceptions_home', 'interceptions_away', 'blocks_home',
       'blocks_away', 'clearances_home', 'clearances_away',
       'keeper_saves_home', 'keeper_saves_away', 'duel_won_home',
       'duel_won_away', 'ground_duels_won_home', 'ground_duels_won_away',
       'aerial_won_home', 'aerial_won_away', 'dribbles_succeeded_home',
       'dribbles_succeeded_away', 'yellow_cards_home', 'yellow_cards_away',
       'red_cards_home', 'red_cards_away'],
      dtype='str')

In [4]:
# p90 minutes

# xG_home, xG_open_play_home, xG_set_play_home, xG_non_penalty_home, xGOT_home

In [5]:
# AVG

# ball_possession_home, 
home_df = df[['homeTeamName', 'homeTeamid', 'ball_possession_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'ball_possesion_home': 'ball_possession'
    }
)

# Create a dataframe with away teams and their goals
away_df = df[['awayTeamName', 'awayTeamid', 'ball_possession_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'ball_possession_away': 'ball_possession'
    }
)

# Stack both dataframes together
avg_possession = pd.concat([home_df, away_df], ignore_index=True)

# Sum goals by team
avg_result = (
    avg_possession
    .groupby(['teamId', 'teamName'], as_index=False)[['ball_possession']]
    .avg()
    .sort_values('ball_pssession', ascending=False)
)

avg_result

AttributeError: 'DataFrameGroupBy' object has no attribute 'avg'

In [6]:
# clean columns
# fouls_home, accurate_passes_home, accurate_long_passes_home, accurate_crosses_home, ground_duels_won_home, aerial_won_home, dribbles_succeeded_home

In [7]:
# Columns to SUM

# home_goals, big_chances_home, big_chances_missed_home, corners_home, total_shots_home, shots_off_target_home, blocked_shots_home, hit_woodwork_home, shots_inside_box_home, shots_outside_box_home,
# passes_home, own_half_passes_home, opposition_half_passes_home, throws_home, touches_opp_box_home, offsides_home, tackles_won_home, interceptions_home, blocks_home, clearances_home, keeper_saves_home,
# duel_won_home, yellow_cards_home, red_cards_home
# Create a dataframe with home teams and their goals
home_df = df[['homeTeamName', 'homeTeamid', 'home_goals', 'big_chances_home', 'big_chances_missed_home', 'corners_home', 'total_shots_home', 'shots_off_target_home', 'blocked_shots_home',
              'hit_woodwork_home', 'shots_inside_box_home', 'shots_outside_box_home', 'passes_home', 'own_half_passes_home', 'opposition_half_passes_home', 'throws_home', 'touches_opp_box_home',
              'offsides_home', 'tackles_won_home', 'interceptions_home', 'blocks_home', 'clearances_home', 'keeper_saves_home', 'duel_won_home', 'yellow_cards_home', 'red_cards_home']].rename(
    columns={
        'homeTeamName': 'teamName',
        'homeTeamid': 'teamId',
        'home_goals': 'goals',
        'big_chances_home': 'big_chances',
        'big_chances_missed_home': 'big_chances_missed',
        'corners_home': 'corners',
        'total_shots_home': 'total_shots',
        'shots_off_target_home': 'shots_off_target',
        'blocked_shots_home': 'blocked_shots',
        'hit_woodwork_home': 'hit_woodwork',
        'shots_inside_box_home': 'shots_inside_box',
        'shots_outside_box_home': 'shots_outside_box',
        'passes_home': 'passes',
        'own_half_passes_home': 'own_half_passes',
        'opposition_half_passes_home': 'opposition_half_passes',
        'throws_home': 'throws',
        'touches_opp_box_home': 'touches_opp_box',
        'offsides_home': 'offsides',
        'tackles_won_home': 'tackles_won',
        'interceptions_home': 'interceptions',
        'blocks_home': 'blocks',
        'clearances_home': 'clearances',
        'keeper_saves_home': 'keeper_saves',
        'duel_won_home': 'duel_won',
        'yellow_cards_home': 'yellow_cards',
        'red_cards_home': 'red_cards'
    }
)

# Create a dataframe with away teams and their goals
away_df = df[['awayTeamName', 'awayTeamid', 'away_goals', 'big_chances_away', 'big_chances_missed_away', 'corners_away', 'total_shots_away', 'shots_off_target_away', 'blocked_shots_away',
              'hit_woodwork_away', 'shots_inside_box_away', 'shots_outside_box_away', 'passes_away', 'own_half_passes_away', 'opposition_half_passes_away', 'throws_away', 'touches_opp_box_away',
              'offsides_away', 'tackles_won_away', 'interceptions_away', 'blocks_away', 'clearances_away', 'keeper_saves_away', 'duel_won_away', 'yellow_cards_away', 'red_cards_away']].rename(
    columns={
        'awayTeamName': 'teamName',
        'awayTeamid': 'teamId',
        'away_goals': 'goals',
        'big_chances_away': 'big_chances',
        'big_chances_missed_away': 'big_chances_missed',
        'corners_away': 'corners',
        'total_shots_away': 'total_shots',
        'shots_off_target_away': 'shots_off_target',
        'blocked_shots_away': 'blocked_shots',
        'hit_woodwork_away': 'hit_woodwork',
        'shots_inside_box_away': 'shots_inside_box',
        'shots_outside_box_away': 'shots_outside_box',
        'passes_away': 'passes',
        'own_half_passes_away': 'own_half_passes',
        'opposition_half_passes_away': 'opposition_half_passes',
        'throws_away': 'throws',
        'touches_opp_box_away': 'touches_opp_box',
        'offsides_away': 'offsides',
        'tackles_won_away': 'tackles_won',
        'interceptions_away': 'interceptions',
        'blocks_away': 'blocks',
        'clearances_away': 'clearances',
        'keeper_saves_away': 'keeper_saves',
        'duel_won_away': 'duel_won',
        'yellow_cards_away': 'yellow_cards',
        'red_cards_away': 'red_cards'
    }
)

# Stack both dataframes together
teams_goals = pd.concat([home_df, away_df], ignore_index=True)

# Sum goals by team
result = (
    teams_goals
    .groupby(['teamId', 'teamName'], as_index=False)[['goals', 'big_chances', 'big_chances_missed', 'corners', 'total_shots', 'shots_off_target', 'blocked_shots', 'hit_woodwork', 'shots_inside_box',
                                                      'shots_outside_box', 'passes', 'own_half_passes', 'opposition_half_passes', 'throws', 'touches_opp_box', 'offsides', 'tackles_won', 'interceptions',
                                                      'blocks', 'clearances', 'keeper_saves', 'duel_won', 'yellow_cards', 'red_cards']]
    .sum()
    .sort_values('goals', ascending=False)
)

result

,teamId,teamName,goals,big_chances,big_chances_missed,corners,total_shots,shots_off_target,blocked_shots,hit_woodwork,...,touches_opp_box,offsides,tackles_won,interceptions,blocks,clearances,keeper_saves,duel_won,yellow_cards,red_cards
26,8570,Germany,7,63,6,0.0,26,6,8,1,...,63,0,19,12,0,8,1,47,0,0
25,8520,Sweden,5,22,4,0.0,13,3,3,0,...,22,3,14,6,1,23,1,41,0,0
12,6713,USA,4,53,4,1.0,16,6,4,0,...,53,2,9,9,3,15,0,65,1,0
11,6710,Mexico,2,20,2,1.0,16,7,5,1,...,20,1,12,8,0,15,2,47,1,1
13,6715,Japan,2,19,0,0.0,10,6,1,0,...,19,0,11,4,1,32,4,28,0,0
9,6708,Netherlands,2,33,0,3.0,10,3,1,0,...,33,1,11,7,0,23,1,46,3,0
20,7804,South Korea,2,24,4,1.0,15,5,4,0,...,24,2,7,9,0,32,3,56,1,0
14,6716,Australia,2,18,1,0.0,9,4,1,0,...,18,1,15,7,12,55,8,42,0,0
5,6262,Morocco,1,13,2,0.0,14,5,6,0,...,13,1,26,5,3,17,4,62,0,0
19,7795,Saudi Arabia,1,10,1,1.0,7,3,1,0,...,10,0,11,9,6,43,9,40,1,0
10,6709,Ivory Coast,1,39,2,3.0,15,8,3,1,...,39,0,14,11,3,29,1,58,3,0
3,5902,Qatar,1,8,1,2.0,6,3,0,0,...,8,0,14,11,9,31,5,36,2,0
0,5796,Uruguay,1,41,2,0.0,27,10,7,1,...,41,6,3,10,1,17,2,42,0,0
1,5810,Canada,1,38,2,2.0,13,5,4,1,...,38,1,23,4,0,21,2,70,2,0
24,8498,Scotland,1,21,2,3.0,9,5,2,1,...,21,1,12,6,4,17,2,59,3,0
21,8256,Brazil,1,22,1,2.0,12,4,3,0,...,22,0,23,5,6,23,2,53,2,0
23,8496,Czechia,1,12,1,0.0,7,3,0,0,...,12,2,9,6,4,21,4,38,0,0
22,8263,Belgium,1,30,2,2.0,15,7,5,1,...,30,0,16,10,8,26,2,52,2,0
28,10255,Egypt,1,25,2,2.0,14,3,8,0,...,25,1,28,12,3,18,3,57,2,0
18,6724,Paraguay,1,11,1,5.0,9,3,5,0,...,11,1,21,10,4,33,3,55,5,0
16,6719,Tunisia,1,10,0,1.0,6,3,1,0,...,10,6,21,6,4,13,1,51,1,0
15,6717,Switzerland,1,42,6,1.0,26,10,9,0,...,42,1,8,7,0,13,3,37,1,0
29,287981,Curacao,1,10,0,0.0,8,6,0,0,...,10,1,16,16,9,25,4,50,0,0
27,10106,Bosnia and Herzegovina,1,14,2,3.0,8,4,1,0,...,14,0,21,10,6,71,1,79,3,0
7,6595,Turkiye,0,51,2,1.0,30,10,12,1,...,51,3,12,4,1,29,2,46,1,0
4,5934,Haiti,0,22,1,1.0,15,9,4,0,...,22,3,12,6,2,20,1,51,1,0
2,5888,Cape Verde,0,6,1,1.0,6,3,2,0,...,6,3,18,15,6,46,7,40,1,0
6,6316,South Africa,0,2,0,2.0,3,1,0,0,...,2,1,14,7,5,17,2,33,2,2
8,6707,Ecuador,0,16,1,1.0,12,8,3,3,...,16,0,21,13,1,18,3,44,1,0
17,6720,Spain,0,51,2,1.0,27,12,8,1,...,51,2,13,6,2,7,1,40,1,0